name: atmgo
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  url_launcher: ^6.3.1
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  google_fonts: ^6.2.1
  mapbox_maps_flutter: ^2.8.0
  connectivity_plus: ^6.1.4
  flutter_dotenv: ^5.2.1
  provider: ^6.1.5
  dio: ^5.8.0+1
  go_router: ^15.1.1
  intl: ^0.20.2
  geolocator: ^14.0.0
  permission_handler: ^12.0.0+1
  get_it: ^8.0.3

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

  build_runner: ^2.4.15
  json_serializable: ^6.9.5
  freezed: ^3.0.6

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true

  assets:
     - assets/icons/
     - assets/images/
     - assets/gif/
     - .env

